// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionOrdersReact.Server.Models;

#nullable disable

namespace SolutionOrdersReact.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260103114701_AddComments")]
    partial class AddComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Urządzenia elektroniczne",
                            IsActive = true,
                            Name = "Elektronika"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Produkty spożywcze",
                            IsActive = true,
                            Name = "Żywność"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Adress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Adress = "ul. Główna 1, Warszawa",
                            IsActive = true,
                            Name = "Jan Kowalski",
                            PhoneNumber = "500-100-200"
                        },
                        new
                        {
                            IdClient = 2,
                            Adress = "ul. Kwiatowa 5, Kraków",
                            IsActive = true,
                            Name = "Anna Nowak",
                            PhoneNumber = "600-200-300"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductId", "CreatedAt");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.GalleryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GalleryItems");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnitOfMeasurement")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUnitOfMeasurement");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Code = "LAP001",
                            Description = "Laptop Dell Inspiron 15",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Laptop Dell",
                            Price = 3500m,
                            Quantity = 10m
                        },
                        new
                        {
                            IdItem = 2,
                            Code = "MON001",
                            Description = "Monitor 24 cale",
                            IdCategory = 1,
                            IdUnitOfMeasurement = 1,
                            IsActive = true,
                            Name = "Monitor Samsung",
                            Price = 800m,
                            Quantity = 15m
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ClientIdClient")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("WorkerIdWorker")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientIdClient");

                    b.HasIndex("WorkerIdWorker");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ItemIdItem")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemIdItem");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("IdUnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnitOfMeasurement"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUnitOfMeasurement");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            IdUnitOfMeasurement = 1,
                            Description = "Sztuki",
                            IsActive = true,
                            Name = "szt"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 2,
                            Description = "Kilogramy",
                            IsActive = true,
                            Name = "kg"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 3,
                            Description = "Litry",
                            IsActive = true,
                            Name = "l"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Worker", b =>
                {
                    b.Property<int>("IdWorker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWorker"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdWorker");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            IdWorker = 1,
                            FirstName = "Piotr",
                            IsActive = true,
                            LastName = "Kowalczyk",
                            Login = "pkowalczyk",
                            Password = "haslo123"
                        },
                        new
                        {
                            IdWorker = 2,
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Wiśniewska",
                            Login = "mwisnieska",
                            Password = "haslo456"
                        });
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Comment", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrdersReact.Server.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrdersReact.Server.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Items")
                        .HasForeignKey("IdUnitOfMeasurement")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Order", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Client", null)
                        .WithMany("Orders")
                        .HasForeignKey("ClientIdClient");

                    b.HasOne("SolutionOrdersReact.Server.Models.Worker", null)
                        .WithMany("Orders")
                        .HasForeignKey("WorkerIdWorker");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.OrderItem", b =>
                {
                    b.HasOne("SolutionOrdersReact.Server.Models.Item", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemIdItem");

                    b.HasOne("SolutionOrdersReact.Server.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Item", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrdersReact.Server.Models.Worker", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
